<nav class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container">
        <a href="<?php echo SERVER_PREFIX; ?>/" class="navbar-btn btn btn-info" role="button">Menü</a>
        <a href="<?php echo SERVER_PREFIX; ?>/report" class="navbar-btn btn btn-info" role="button">Auswertung</a>
        <a href="<?php echo SERVER_PREFIX; ?>/upload" class="navbar-btn btn btn-info" role="button">Übungen
            Hochladen</a>
    </div>
</nav>

</body>
</html>