<?php
/**
 * Created by PhpStorm.
 * User: Ezydenias
 * Date: 6/13/2017
 * Time: 20:32
 */

/** @var \Ezydenias\Vokabeltrainer\Lesson $lesson */
/** @var mixed[] $question */
/** @var int $step */
/** @var string $lessonName */
/** @var string $next */
/** @var string $givenAnswer */
/** @var bool $isCorrect */
/** @var bool $reverse */

$next = $next . ($reverse ? '/reverse' : '');

?><!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vokabelübung &gt; <?php echo $lessonName; ?></title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="panel panel-success">
    <div class="panel-heading">
        <h1><?php echo $question['question']; ?></h1>
        <hr>
    </div>

    <div class="panel-body">
        <?php foreach ($question['answers'] as $i => $answer): ?>
            <div
                <?php if ($answer === $givenAnswer): ?> class="alert alert-<?php echo $isCorrect ? 'success' : 'danger'; ?>"
                    role="alert" <?php else: ?>class="well well-sm"<?php endif; ?>>
                <strong><?php echo $answer; ?></strong>
            </div>
        <?php endforeach; ?>
        <a href="<?php echo $next; ?>" class="btn btn-info" role="button">Weiter</a>
    </div>

</div>
</body>
</html>