<?php
/**
 * Created by PhpStorm.
 * User: Ezydenias
 * Date: 6/13/2017
 * Time: 20:32
 */

/** @var \Ezydenias\Vokabeltrainer\Lesson $lesson */
/** @var mixed[] $question */
/** @var int $step */
/** @var string $lessonName */
/** @var string $action */
/** @var bool $reverse */

$reverseAction = $action . (!$reverse ? '/reverse' : '');
$action = $action . ($reverse ? '/reverse' : '');

?><!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vokabelübung &gt; <?php echo $lessonName; ?></title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h1><?php echo $question['question']; ?>
            <a href="<?php echo $reverseAction; ?>" class="pull-right btn btn-default">Drehen</a>
        </h1>
        <hr>
    </div>
    <form action="<?php echo $action; ?>" method="post" autocomplete="off">
        <input type="hidden" name="available" value="<?php echo implode('|', $question['answers']); ?>">
        <?php foreach ($question['answers'] as $i => $answer): ?>
            <div class="well">
                <label for="answer<?php echo $i; ?>">
                    <input id="answer<?php echo $i; ?>" name="answer" type="radio" value="<?php echo $answer; ?>"/>
                    <?php echo $answer; ?>
                </label>
            </div>
        <?php endforeach; ?>
        <button class="btn btn-info" name="check" value="1">Prüfen</button>
    </form>
</div>
</body>
</html>