<?php
/**
 * Created by PhpStorm.
 * User: Ezydenias
 * Date: 6/13/2017
 * Time: 20:32
 */

/** @var \Ezydenias\Vokabeltrainer\Lesson $lesson */
/** @var int $step */
/** @var string $lessonName */
/** @var string $next */

?><!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vokabelübung &gt; <?php echo $lessonName; ?></title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="panel panel-success">
    <div class="panel-heading">
        <div class="progress">
            <div
                    class="progress-bar progress-bar-success" role="progressbar"
                    aria-valuenow="<?php echo $lesson->getScore(); ?>"
                    aria-valuemin="0"
                    aria-valuemax="<?php echo $lesson->getLength(); ?>"
                    style="width: <?php echo $lesson->getScore() / $lesson->getLength() * 100; ?>%;">
                <p><?php echo $lesson->getScore(); ?> von <?php echo $lesson->getLength(); ?></p>
            </div>
        </div>
        <a href="/" class="btn btn-info" role="button">Menü</a>
    </div>
</body>
</html>