<?php
/**
 * Created by PhpStorm.
 * User: Ezydenias
 * Date: 6/13/2017
 * Time: 20:32
 */

/** @var \Ezydenias\Vokabeltrainer\Lesson $lesson */
/** @var mixed[] $question */
/** @var int $step */
/** @var string $lessonName */
/** @var string $next */
/** @var string $givenAnswer */
/** @var bool $isCorrect */
/** @var bool $reverse */

$next = $next . ($reverse ? '/reverse' : '');

$title = 'Vokabelübung &gt; ' . $lessonName;

require __DIR__ . '/includes/head.phtml';

?>
    <div class="container">
        <h2><?php echo $question['question']; ?></h2>
        <?php foreach ($question['answers'] as $i => $answer): ?>
            <div
                <?php if ($answer === $givenAnswer): ?> class="alert alert-<?php echo $isCorrect ? 'success' : 'danger'; ?>"
                    role="alert" <?php else: ?>class="well well-sm"<?php endif; ?>>
                <strong><?php echo $answer; ?></strong>
            </div>
        <?php endforeach; ?>
        <a href="<?php echo SERVER_PREFIX . $next; ?>" class="btn btn-info" role="button">Weiter</a>
    </div>

<?php require __DIR__ . '/includes/foot.phtml'; ?>